const { QueryType } = require('tablestore');

const {
  MATCH_QUERY,
  MATCH_PHRASE_QUERY,
  TERM_QUERY,
  RANGE_QUERY,
  PREFIX_QUERY,
  BOOL_QUERY,
  CONST_SCORE_QUERY,
  FUNCTION_SCORE_QUERY,
  NESTED_QUERY,
  WILDCARD_QUERY,
  MATCH_ALL_QUERY,
  GEO_BOUNDING_BOX_QUERY,
  GEO_DISTANCE_QUERY,
  GEO_POLYGON_QUERY,
  TERMS_QUERY,
  EXISTS_QUERY,
} = QueryType;

module.exports = {
  MATCH_QUERY,
  MATCH_PHRASE_QUERY,
  TERM_QUERY,
  RANGE_QUERY,
  PREFIX_QUERY,
  BOOL_QUERY,
  CONST_SCORE_QUERY,
  FUNCTION_SCORE_QUERY,
  NESTED_QUERY,
  WILDCARD_QUERY,
  MATCH_ALL_QUERY,
  GEO_BOUNDING_BOX_QUERY,
  GEO_DISTANCE_QUERY,
  GEO_POLYGON_QUERY,
  TERMS_QUERY,
  EXISTS_QUERY,
};
